apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-klage-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  ingresses:
    - https://familie-klage.dev.nav.no
  azure:
    application:
      enabled: true
      replyURLs:
        - https://familie-klage.dev.intern.nav.no/auth/openid/callback
      claims:
        groups:
          - id: "01166863-22f1-4e16-9785-d7a05a22df74" # 0000-GA-Enslig-Forsorger-Beslutter
          - id: "ee5e0b5e-454c-4612-b931-1fe363df7c2c" # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: "19dcbfde-4cdb-4c64-a1ea-ac9802b03339" # 0000-GA-Enslig-Forsorger-Veileder
          - id: "de44052d-b062-4497-89a2-0c85b935b808" # 0000-GA-GOSYS_UTVIDET
          - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
          - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-klage-redis
        - application: familie-brev
        - application: familie-klage
  envFrom:
    - secret: familie                       # Henter ut EF_SAK_SCOPE
    - secret: familie-klage-frontend-redis  # Henter ut REDIS_PASSWORD
    - secret: familie-klage-frontend        # Ulike secrets
  env:
    - name: APP_VERSION
      value: "{{version}}"
    - name: ENV
      value: preprod