apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-klage-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
  port: 8020
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://familie-klage.intern.nav.no
  azure:
    application:
      enabled: true
      replyURLs:
        - https://familie-klage.intern.nav.no/auth/openid/callback
      claims:
        groups:
          - id: 847e3d72-9dc1-41c3-80ff-f5d4acdd5d46 # 0000-GA-Barnetrygd
          - id: 7a271f87-39fb-468b-a9ee-6cf3c070f548 # 0000-GA-Barnetrygd-Beslutter
          - id: 199c2b39-e535-4ae8-ac59-8ccbee7991ae # 0000-GA-Barnetrygd-Veileder
          - id: e40090eb-c2fb-400e-b412-e9084019a73b # 0000-GA-Kontantstotte
          - id: 4e7f23d9-5db1-45c0-acec-89c86a9ec678 # 0000-GA-Kontantstotte-Beslutter
          - id: 54cd86b8-2e23-48b2-8852-b05b5827bb0f # 0000-GA-Kontantstotte-Veileder
          - id: 31778fd8-3b71-4867-8db6-a81235fbe001 # 0000-GA-Enslig-Forsorger-Veileder
          - id: 6406aba2-b930-41d3-a85b-dd13731bc974 # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: 5fcc0e1d-a4c2-49f0-93dc-27c9fea41e54 # 0000-GA-Enslig-Forsorger-Beslutter
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-sak
        - application: familie-brev
        - application: familie-klage
  envFrom:
    - secret: familie                       # Henter ut FAMILIE-KLAGE
    - secret: familie-klage-frontend        # Ulike secrets
  env:
    - name: APP_VERSION
      value: "{{version}}"
    - name: ENV
      value: production
  redis:
    - instance: sessions
      access: readwrite
    - instance: lookup
      access: read
