name: Build app

on: [pull_request, workflow_dispatch]
env:
  IMAGE: ghcr.io/navikt/familie-klage-frontend:${{ github.sha }}

jobs:
  build:
    name: Bygg app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v4
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # ratchet:actions/setup-node@v4
        with:
          node-version: "24"
          cache: yarn
          registry-url: "https://npm.pkg.github.com"
      - name: Yarn install
        run: yarn --prefer-offline --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Yarn build
        run: yarn build
      - name: Yarn test
        run: yarn test
