name: Build app

on: [pull_request, workflow_dispatch]
env:
  IMAGE: ghcr.io/navikt/familie-klage-frontend:${{ github.sha }}

jobs:
  build:
    name: Bygg app og Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bygg app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: docker build -t ${IMAGE} . --build-arg NPM_TOKEN=${NPM_TOKEN}