name: Build app

on: [pull_request, workflow_dispatch]
env:
  IMAGE: ghcr.io/navikt/familie-klage-frontend:${{ github.sha }}

jobs:
  build:
    name: Bygg app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
          registry-url: "https://npm.pkg.github.com"
        if: github.actor != 'dependabot[bot]'
      - name: Yarn install
        run: yarn --prefer-offline --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SALSA_CREDENTIALS }}
      - name: Yarn build
        run: yarn build